---
# Configure the instance as a web server with varnish
- name: Install http, php, etc
  sudo: True
  apt: "name={{ item }} state=present"
  with_items:
   - apache2
   - php5
   - php5-mysql
   - libapache2-mod-php5
   - php5-mcrypt
   - php-apc
   - php5-curl
   - php5-common
   - openssl
   - git
   - varnish

- name: copy config files needed
  sudo: True
  copy: src=/Users/matts/Documents/ansible/mpg/roles/lamp/files/{{ item.src }} dest={{ item.dest }} group=root owner=root mode=0640
  with_items:
    - { src: 'default.vcl', dest: '/etc/varnish/default.vcl' }
    - { src: 'default', dest: '/etc/apache2/sites-available/default.conf' }

- name: enable sites
  sudo: True
  command: a2ensite {{ item }}
  with_items:
    - default
  notify: restart apache

- name: disable things
  sudo: True
  command: a2dissite {{ item.site }} removes={{ item.file }}
  with_items:
    - { site: '000-default.conf', file: '/etc/apache2/sites-enabled/000-default.conf' }
  notify: restart apache

- name: restart varnish
  service: name=varnish state=restarted

- name: restart apache
  service: name=apache2 state=restarted