---
- name: Add Joe's key
  lineinfile: dest=/home/ubuntu/.ssh/authorized_keys line="PUBKEY GOES HERE"

- name: Add Sally's key
  lineinfile: dest=/home/ubuntu/.ssh/authorized_keys line="PUBKEY GOES HERE"

- name: Create SSH key
  command: ssh-keygen -t dsa -N "" -C "user@local.host" -f id_rsa chdir=.ssh

- name: Run updates
  apt: update_cache=yes upgrade=yes